#!/bin/sh

# Processing
while true
do
  HEADERS="$(mktemp)"

  # Get an event. The HTTP request will block until one is received
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")

  # Extract request ID by scraping response headers received above
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  # Download and prepare the project files
  SHOULD_CONTINUE=$(/opt/bin/php -f "$LAMBDA_TASK_ROOT/bootstrap.php" "$EVENT_DATA" "setup.php")

  if [[ $SHOULD_CONTINUE = 'false' ]]; then
    echo "Exiting script early. Warming request detected"
    curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "{}"
    continue
  fi

  # Move into the project code as Pest needs to be executed from there
  cd "/tmp/project"
  chmod -R 777 .

  # Now let's run the tests!
  RESPONSE=$(/opt/bin/php -f "$LAMBDA_TASK_ROOT/bootstrap.php" "$EVENT_DATA" "runTests.php")

  # Send the response
  curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "$RESPONSE"
done
