#!/bin/sh

# Processing
while true
do
  HEADERS="$(mktemp)"

  # Get an event. The HTTP request will block until one is received
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")

  echo $EVENT_DATA

  # Extract request ID by scraping response headers received above
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  # Run the handler function from the script
  /opt/bin/php -f "$LAMBDA_TASK_ROOT/bootstrap.php" $EVENT_DATA

  if [[ $(/opt/bin/php -f "$LAMBDA_TASK_ROOT/checkForWarming.php") -gt 0 ]]; then
      curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "{}"
      break
  fi

  # Get the test command
  TEST_COMMAND=$(/opt/bin/php -f "$LAMBDA_TASK_ROOT/getTestCommand.php" $EVENT_DATA)

  echo $TEST_COMMAND

  # Move into the project code as Pest needs to be executed from there
  cd "/tmp/project"

  chmod -R 777 .

  PEST_OUTPUT=$(eval $TEST_COMMAND)
  PEST_EXIT_CODE=$?

  RESPONSE=$(/opt/bin/php -f "$LAMBDA_TASK_ROOT/buildResponse.php" "$PEST_OUTPUT" "$PEST_EXIT_CODE" "$EVENT_DATA")

  # Send the response
  curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "$RESPONSE"
done
