<?php

namespace Pest\Parallel\Serverless\Sidecar\Functions;

use Hammerstone\Sidecar\LambdaFunction;
use Hammerstone\Sidecar\Package;

final class RunTest extends LambdaFunction
{
    public function handler(): string
    {
        return 'noop';
    }

    public function package(): Package
    {
        return Package::make()->includeExactly([
            // Place the Runtime files at the root of the lambda function.
            __DIR__ . '/RunTest/Runtime' => '/'
        ]);
    }

    public function preparePayload($payload)
    {
        dd($payload);
        return parent::preparePayload($payload); // TODO: Change the autogenerated stub
    }

    public function timeout(): int
    {
        return 1000 * 60 * 5;
    }
}
